# Generated by Django 4.2.5 on 2023-10-01 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('playas', 'Playas'), ('hoteles', 'Hoteles'), ('otro', 'Otro')], default='playas', max_length=15)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(max_length=40)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('imagenInstrumento', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario_id', '-fechaPublicacion'],
            },
        ),
    ]
