# Generated by Django 4.2.5 on 2023-10-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
