# Generated by Django 4.2.5 on 2023-10-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_rename_usuario_id_publicacion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='imagenInstrumento',
            new_name='imagenPublicacion',
        ),
    ]
