# Generated by Django 4.2.5 on 2023-10-03 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_rename_imageninstrumento_publicacion_imagenpublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=70)),
                ('mensaje', models.TextField(blank=True, max_length=300, null=True)),
                ('comentarioFecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.publicacion')),
            ],
            options={
                'ordering': ['-comentarioFecha'],
            },
        ),
    ]
