# Generated by Django 4.2.5 on 2023-10-03 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0005_alter_comentario_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, max_length=300, null=True)),
                ('fechaEnvio', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emisores', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to='AppBlog.publicacion')),
            ],
            options={
                'ordering': ['-fechaEnvio'],
            },
        ),
    ]
