# Generated by Django 4.2.5 on 2023-10-03 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0006_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to=settings.AUTH_USER_MODEL),
        ),
    ]
