# Generated by Django 4.2.5 on 2023-10-03 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0007_alter_mensaje_receptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='receptor',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
