# Generated by Django 4.2.5 on 2023-10-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
